import React from "react";
import './css/space.css';

const Space = () => {

    return (
    <div className="space">
        <div className="space-wrapper">
            <h1>Entdecke das Weltall!</h1>
            <h2>Sonne, Mond und Erde</h2>
            <p>Unser Sonnensystem ist voller faszinierender Himmelskörper, von denen die Erde, der Mond und die Sonne nur einige sind. Tauche ein in die Welt der Astronomie und entdecke die Geheimnisse und Wunder, die unseren Planeten und seine Begleiter ausmachen!</p>
            <p>Unsere Erde: Die Erde, unser Zuhause, ist der dritte Planet der Sonne und der einzige bekannte Ort im Universum, der Leben beherbergt. Mit einer Vielzahl an Ökosystemen, Landschaften, Klimazonen und einem einzigartigen Magnetfeld bietet die Erde eine unglaubliche Vielfalt an Lebensformen. Entdecke die erstaunlichen Phänomene wie die Jahreszeiten, Wetterphänomene, Ozeane und Kontinente, die unseren Planet so einzigartig machen.</p>
            <p>Der Mond: Unser treuer Begleiter, der Mond, ist der natürliche Satellit der Erde. Mit seiner beeindruckenden Oberfläche, die von Kratern und Bergen geprägt ist, fasziniert der Mond die Menschheit seit Jahrtausenden, unter anderem durch seine unterschiedlichen Phasen. Der einzige Himmelskörper, auf den die Menschen jemals hingereist sind, erzeugt gleichzeitig Ebbe und Flut.</p>
            <p>Die Sonne: Die Sonne, der strahlende Stern in unserem Sonnensystem, ist die Quelle aller Lebens und Licht. Die unglaubliche Größe und Hitze der Sonne begrüßt uns Tag für Tag mit warmem Licht. Durch das Gegenspiel von der Sonne und dem Mond entstehen Sonnen- und Mondfinsternisse. Erfahre mehr über ihre Zusammensetzung, Energieerzeugung und die Auswirkungen auf das Leben auf der Erde!</p>
            <h2>Unser Sonnensystem </h2>
            <p>Unser Sonnensystem ist ein System, das die Sonne, acht Planeten, zahlreiche Zwergplaneten, Monde und andere Himmelskörper umfasst. Die Sonne ist der Mittelpunkt des Sonnensystems und übt eine gravitative Anziehungskraft auf die um sie umkreisenden Objekte aus. Jeder Planet hat seine eigenen einzigartigen Eigenschaften, Umlaufbahnen und Monde. Um sich die Planeten unseres Sonnensystems zu merken, hilft folgender Spruch: “<b>M</b>ein <b>V</b>ater <b>E</b>rklärt <b>M</b>ir <b>J</b>eden <b>S</b>onntag <b>U</b>nseren <b>N</b>achthimmel”</p>
            <div className="solar-system">
                <p><b>M</b>erkur: Der innerste und kleinste Planet in unserem Sonnensystem heißt Merkur. Er hat keinen Mond und umkreist die Sonne in nur 88 Tagen. Aufgrund seiner Nähe zur Sonne erreicht Merkur extrem hohe Temperaturen von bis zu 430°C tagsüber und kann nachts auf -180°C abkühlen. Merkur hat eine felsige Oberfläche mit Kratern, Schluchten und ebenen Flächen. Seine Atmosphäre ist dünn und besteht hauptsächlich aus Helium und Spuren von Sauerstoff und Natrium.</p>
                <p><b>V</b>enus: Die Venus, benannt nach der römischen Göttin der Liebe und Schönheit, ist der zweite Planet in unserem Sonnensystem und der hellste am Nachthimmel. Mit einer durchschnittlichen Oberflächentemperatur von etwa 465°C ist sie der heißeste Planet im Sonnensystem, obwohl Merkur näher an der Sonne liegt. Die Venus ist von einer dicken Wolkendecke aus Schwefelsäure umgeben, die das Sonnenlicht reflektiert und den Planeten in einem intensiven Gelb erstrahlen lässt. Aufgrund der extremen Temperaturen und des starken atmosphärischen Drucks ist die Oberfläche der Venus eine lebensfeindliche Umgebung</p>
                <p><b>E</b>rde: Er ist der dritte Planet in unserem Sonnensystem und der einzige bekannte Planet, auf dem Leben existiert und flüssiges Wasser vorkommt. Sie hat einen durchschnittlichen Abstand von etwa 150 Mio. Kilometern zur Sonne und eine Umlaufzeit von etwa 365 Tagen. Die Erde besitzt viele komplexe Ökosysteme und eine dichte Atmosphäre. Diese enthält Sauerstoff und andere lebenswichtige Gase. </p>
                <p><b>M</b>ars: Auch bekannt als der Rote Planet, ist er der vierte Planet in unserem Sonnensystem und der äußere Nachbar der Erde. Er ist nach dem römischen Kriegsgott benannt und hat eine auffällig rötliche Färbung aufgrund des hohen Eisengehalts in seinem Boden. Der Mars hat eine dünnere Atmosphäre als die Erde und ist durch seine charakteristischen polaren Eiskappen und ausgetrockneten Flussbetten gekennzeichnet, die auf einst flüssiges Wasser hinweisen. Er ist Ziel für die Erforschung und Raumfahrtmissionen, da er möglicherweise Spuren von Leben beherbergt oder in der Zukunft besiedelt werden könnte.</p>
                <p><b>J</b>upiter: Der Jupiter, der größte Planet in unserem Sonnensystem. ist ein Gasriese und der fünfte Planet von der Sonne aus gesehen. Er ist bekannt für sein markantes Aussehen mit breiten Wolken-Gürteln und dem Großen Roten Fleck, einem riesigen Sturm. Jupiter hat eine immense Gravitationskraft und viele Monde, darunter den größten Mond im Sonnensystem, Ganymed. Forscher interessieren sich besonders für Jupiter, da er Einblicke in die Entstehungsgeschichte unseres Sonnensystems bietet.</p>
                <p><b>S</b>aturn: Er ist der sechste Planet in unserem Sonnensystem und sticht durch seine beeindruckenden Ringe heraus, die ihn umgeben. Diese Ringe bestehen hauptsächlich aus Eis und Gesteinsbrocken in verschiedenen Größen. Saturn ist ein Gasriese und besitzt eine dichte Atmosphäre, die hauptsächlich aus Wasserstoff und Helium besteht. Er ist der zweitgrößte Planet im Sonnensystem und hat eine markante goldene Farbe. Saturn hat auch eine Vielzahl von Monden, darunter Titan, welcher die einzig bekannte Atmosphäre auf einem Mond besitzt.</p>
                <p><b>U</b>ranus: Der drittgrößte Planet nach Durchmesser ist ein Eisriese und besteht hauptsächlich aus Wasserstoff und Helium, jedoch mit einem hohen Anteil an Methan, der ihm die charakteristische blau-grüne Farbe verleiht. Seine ungewöhnliche Achsenneigung führt dazu, dass Uranus auf seiner Seite rollt. Auch der Uranus besitzt ein Ringsystem und außerdem 27 Monde</p>
                <p><b>N</b>eptun: Benannt nach dem römischen Gott des Meeres, ist Neptun der achte und äußerste Planet unseres Sonnensystems. Wie Uranus ist Neptun ein Eisriese, jedoch dichter und massereicher. Seine Umlaufbahn um die Sonne dauert etwa 165 Jahre und befindet sich ca. 4,5 Mrd. Kilometer von der Sonne entfernt. Der größte seiner 14 Mode heißt Triton, der rückläufig um den Planet kreist.</p>
            </div>
            
            <h2>Die Milchstraße </h2>
            <p>Die Milchstraße ist unsere galaktische Heimat, ein riesiges System aus Milliarden von Sternen, Gas, Staub und Dunkler Materie. Als Spiralgalaxie hat sie einen Durchmesser von etwa 100.000 Lichtjahren und eine Masse von ungefähr 1,5 Billionen Sonnenmassen. Die Milchstraße gehört zu den Balkengalaxien. Sie besitzt im Zentrum einen Bulge. Dieser wirkt aufgrund seiner hohen Dichte heller. Um diesen Bulge befinden sich vier Spiralarme, die sich primär durch junge Sterne und Gaswolken abzeichnen, wobei sich in zwei Armen auch ältere Sterne befinden. Unsere Sonne liegt in einem der äußeren Arme, etwa 25.000 Lichtjahre vom galaktischen Zentrum entfernt.</p>
            <p>Im Zentrum der Milchstraße existiert ein supermassives schwarzes Loch namens Sagittarius A*, welches sich im Sternbild Schütze befindet. Sie ist 4,15 Mio. massereicher als unsere Sonne und wurde in den 1990er Jahren entdeckt. Erste Aufnahmen wurden 2017 durch das Event Horizon Telescope gemacht.</p>
            <p>Die Erforschung der Milchstraße ist eine der Hauptaufgaben der modernen Astronomie. Astronomen nutzen Teleskope auf der Erde und im Weltraum, um die Struktur, Zusammensetzung und Entwicklung unserer Galaxie zu untersuchen. Durch die Analyse von Sternbewegungen, interstellarem Gas und anderen galaktischen Eigenschaften können Wissenschaftler wichtige Erkenntnisse über die Entstehung und Evolution von Galaxien gewinnen.</p>

        	<h2>Ferne Galaxien</h2>
            <p>Ferne Galaxien sind faszinierende kosmische Objekte, die oft weit entfernt von unserer Milchstraße liegen. Diese riesigen Ansammlungen von Sternen, Gas, Staub und Dunkler Materie bieten einen faszinierenden Einblick in die Vielfalt und die Entwicklung des Universums.</p>
            <p>Eine der bemerkenswertesten Eigenschaften ferner Galaxien ist ihre Vielfalt. Es gibt verschiedene Arten von Galaxien, darunter elliptische Galaxien, Spiralgalaxien und irreguläre Galaxien. Jede dieser Galaxientypen hat ihre eigenen charakteristischen Merkmale, die durch ihre Form, Struktur und Sternbildungsraten bestimmt werden.</p>
            <p>Ein weiteres faszinierendes Merkmal ferner Galaxien ist ihre Entfernung. Da das Licht eine endliche Geschwindigkeit hat, sehen wir Galaxien so, wie sie in der Vergangenheit waren, als das Licht aus ihnen zu uns reiste. Dies ermöglicht es Astronomen, in die Vergangenheit des Universums zurückzublicken und die Entwicklung und Evolution von Galaxien im Laufe der Zeit zu studieren.</p>
            <p>Ferne Galaxien spielen auch eine wichtige Rolle bei unserem Verständnis der kosmischen Struktur und der Entstehung des Universums. Durch die Untersuchung ihrer Verteilung und Bewegung können Wissenschaftler Modelle erstellen, die helfen, die Entstehung und Entwicklung des Universums zu erklären.</p>
            <p>Darüber hinaus dienen ferne Galaxien als Laboratorien für die Erforschung verschiedener astrophysikalischer Phänomene, darunter Supernovaexplosionen, aktive galaktische Kerne und die Entstehung von Schwarzen Löchern. Durch die Beobachtung und Analyse ferner Galaxien können Wissenschaftler wichtige Erkenntnisse über die Physik und die fundamentalen Kräfte des Universums gewinnen.</p>
            <p>Insgesamt bieten ferne Galaxien einen faszinierenden Einblick in die Natur des Universums und spielen eine entscheidende Rolle bei unserem Streben, die Geheimnisse des Kosmos zu entschlüsseln. Ihre Untersuchung und Erforschung wird weiterhin dazu beitragen, unser Verständnis des Universums und unsere eigene Position darin zu vertiefen.</p>
            <p>Ferne Galaxien, die sich weit außerhalb unserer Milchstraße befinden, faszinieren Wissenschaftler und Amateurastronomen gleichermaßen. Besonders interessant für Wissenschaftler ist die Andromedagalaxie. Ihre Nähe zur Milchstraße ermöglicht ihnen die umfangreiche Erforschung, die auch Rückschlüsse über die Geschichte der Milchstraße ermöglicht. Mit einer Entfernung von 2,5 Mio. Lichtjahren ist sie das entfernteste Objekt, das mit bloßem Auge am Nachthimmel beobachtet werden kann. Ihre Masse wird auf 0,7 bis 2,5 Billionen Sonnenmassen geschätzt und damit etwas so massereich wie die Milchstraße, während der Durchmesser der Andromedagalaxie doppelt so groß ist.</p>
        
            <h2>Ferne Sterne(nsysteme)</h2>
            <p></p>
        </div>
    </div>
    );
};

export default Space;